/* This file was generated by SableCC (http://www.sablecc.org/). */

package cc.parser;

import cc.node.*;
import cc.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTLBrack(@SuppressWarnings("unused") TLBrack node)
    {
        this.index = 0;
    }

    @Override
    public void caseTRBrack(@SuppressWarnings("unused") TRBrack node)
    {
        this.index = 1;
    }

    @Override
    public void caseTPoints(@SuppressWarnings("unused") TPoints node)
    {
        this.index = 2;
    }

    @Override
    public void caseTPoint(@SuppressWarnings("unused") TPoint node)
    {
        this.index = 3;
    }

    @Override
    public void caseTCatg(@SuppressWarnings("unused") TCatg node)
    {
        this.index = 4;
    }

    @Override
    public void caseTNumero(@SuppressWarnings("unused") TNumero node)
    {
        this.index = 5;
    }

    @Override
    public void caseTTitulo(@SuppressWarnings("unused") TTitulo node)
    {
        this.index = 6;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 7;
    }
}
