/* This file was generated by SableCC (http://www.sablecc.org/). */

package cc.lexer;

import java.io.*;
import cc.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private String customSource;
    private int customIndex;
    private boolean customLoaded;

    private enum CustomMode
    {
        NONE,
        AFTER_LBRACK,
        AFTER_MIN,
        AFTER_SEG,
        AFTER_POINT,
        AFTER_MS,
        AFTER_CATG,
        AFTER_META_TEXT,
        AFTER_META_RBRACK,
        AFTER_TIME_RBRACK,
        AFTER_TIME_TEXT
    }

    private CustomMode customMode = CustomMode.NONE;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    private void loadCustomSource() throws IOException
    {
        if(this.customLoaded)
        {
            return;
        }

        StringBuilder builder = new StringBuilder();
        int c;
        while((c = this.in.read()) != -1)
        {
            builder.append((char) c);
        }

        this.customSource = builder.toString();
        this.customIndex = 0;
        this.customLoaded = true;
        this.line = 1;
        this.pos = 1;
        this.cr = false;
    }

    private boolean customAtEnd()
    {
        return this.customSource == null || this.customIndex >= this.customSource.length();
    }

    private char customPeekChar()
    {
        return this.customSource.charAt(this.customIndex);
    }

    private void customConsumeChar()
    {
        char c = this.customSource.charAt(this.customIndex++);
        if(c == '\r')
        {
            if(this.customIndex < this.customSource.length() && this.customSource.charAt(this.customIndex) == '\n')
            {
                this.customIndex++;
            }

            this.line++;
            this.pos = 1;
            this.cr = true;
            return;
        }

        if(c == '\n')
        {
            if(!this.cr)
            {
                this.line++;
            }

            this.pos = 1;
            this.cr = false;
            return;
        }

        this.pos++;
        this.cr = false;
    }

    private void customSkipIgnorable()
    {
        while(!customAtEnd())
        {
            char c = customPeekChar();
            if(c == ' ' || c == '\t' || c == '\f' || c == '\r' || c == '\n')
            {
                customConsumeChar();
                continue;
            }

            break;
        }
    }

    private LexerException customError(String text, int line, int pos)
    {
        return new LexerException(new InvalidToken(text, line, pos),
            "[" + line + "," + pos + "] Unknown token: " + text);
    }

    private Token customReadAfterLBracket() throws LexerException
    {
        customSkipIgnorable();

        if(customAtEnd())
        {
            return new EOF(this.line, this.pos);
        }

        int startLine = this.line;
        int startPos = this.pos;
        char c = customPeekChar();

        if(Character.isDigit(c))
        {
            int start = this.customIndex;
            while(!customAtEnd() && Character.isDigit(customPeekChar()))
            {
                customConsumeChar();
            }

            this.customMode = CustomMode.AFTER_MIN;
            return new TMin(this.customSource.substring(start, this.customIndex), startLine, startPos);
        }

        if(c == ']')
        {
            this.customMode = CustomMode.NONE;
            customConsumeChar();
            return new TCatg("", startLine, startPos);
        }

        int start = this.customIndex;
        while(!customAtEnd())
        {
            c = customPeekChar();
            if(c == ':' || c == ']' || c == '\r' || c == '\n')
            {
                break;
            }
            customConsumeChar();
        }

        this.customMode = CustomMode.AFTER_CATG;
        return new TCatg(this.customSource.substring(start, this.customIndex).trim(), startLine, startPos);
    }

    private Token customReadTextUntil(char terminator, CustomMode nextMode, boolean allowEmpty, boolean keepWhitespace) throws LexerException
    {
        if(customAtEnd())
        {
            this.customMode = CustomMode.NONE;
            return new TTitulo("", this.line, this.pos);
        }

        int startLine = this.line;
        int startPos = this.pos;

        if(!keepWhitespace)
        {
            while(!customAtEnd())
            {
                char c = customPeekChar();
                if(c == ' ' || c == '\t' || c == '\f')
                {
                    customConsumeChar();
                    startLine = this.line;
                    startPos = this.pos;
                    continue;
                }
                break;
            }
        }

        if(customAtEnd())
        {
            this.customMode = nextMode;
            return new TTitulo("", startLine, startPos);
        }

        char c = customPeekChar();
        if(c == '\r' || c == '\n' || c == terminator)
        {
            if(allowEmpty)
            {
                this.customMode = nextMode;
                return new TTitulo("", startLine, startPos);
            }

            throw customError(String.valueOf(c), startLine, startPos);
        }

        int start = this.customIndex;
        while(!customAtEnd())
        {
            c = customPeekChar();
            if(c == terminator || c == '\r' || c == '\n')
            {
                break;
            }
            customConsumeChar();
        }

        this.customMode = nextMode;
        return new TTitulo(this.customSource.substring(start, this.customIndex), startLine, startPos);
    }

    private Token nextCustomToken() throws LexerException, IOException
    {
        loadCustomSource();

        while(true)
        {
            if(this.customMode == CustomMode.AFTER_TIME_TEXT)
            {
                return customReadTextUntil('\n', CustomMode.NONE, true, true);
            }

            if(this.customMode == CustomMode.AFTER_META_TEXT)
            {
                return customReadTextUntil(']', CustomMode.AFTER_META_RBRACK, true, true);
            }

            if(this.customMode == CustomMode.AFTER_META_RBRACK)
            {
                customSkipIgnorable();
                if(customAtEnd())
                {
                    return new EOF(this.line, this.pos);
                }

                int startLine = this.line;
                int startPos = this.pos;
                if(customPeekChar() == ']')
                {
                    customConsumeChar();
                    this.customMode = CustomMode.NONE;
                    return new TRBrack(startLine, startPos);
                }

                this.customMode = CustomMode.NONE;
                continue;
            }


        if(this.customMode == CustomMode.AFTER_TIME_RBRACK)
        {
            customSkipIgnorable();
            if(customAtEnd())
            {
                return new EOF(this.line, this.pos);
            }

            int startLine = this.line;
            int startPos = this.pos;
            if(customPeekChar() == ']')
            {
                customConsumeChar();
                this.customMode = CustomMode.AFTER_TIME_TEXT;
                return new TRBrack(startLine, startPos);
            }

            throw customError(String.valueOf(customPeekChar()), startLine, startPos);
        }
            customSkipIgnorable();
            if(customAtEnd())
            {
                return new EOF(this.line, this.pos);
            }

            int startLine = this.line;
            int startPos = this.pos;
            char c = customPeekChar();

            switch(this.customMode)
            {
                case NONE:
                    if(c == '[')
                    {
                        customConsumeChar();
                        this.customMode = CustomMode.AFTER_LBRACK;
                        return new TLBrack(startLine, startPos);
                    }

                    if(c == ']')
                    {
                        customConsumeChar();
                        return new TRBrack(startLine, startPos);
                    }

                    if(c == ':')
                    {
                        customConsumeChar();
                        return new TPoints(startLine, startPos);
                    }

                    if(c == '.')
                    {
                        customConsumeChar();
                        return new TPoint(startLine, startPos);
                    }

                    throw customError(String.valueOf(c), startLine, startPos);

                case AFTER_LBRACK:
                    return customReadAfterLBracket();

                case AFTER_MIN:
                    if(c == ':')
                    {
                        customConsumeChar();
                        this.customMode = CustomMode.AFTER_SEG;
                        return new TPoints(startLine, startPos);
                    }
                    throw customError(String.valueOf(c), startLine, startPos);

                case AFTER_SEG:
                    if(Character.isDigit(c))
                    {
                        int start = this.customIndex;
                        while(!customAtEnd() && Character.isDigit(customPeekChar()))
                        {
                            customConsumeChar();
                        }

                        this.customMode = CustomMode.AFTER_POINT;
                        return new TSeg(this.customSource.substring(start, this.customIndex), startLine, startPos);
                    }
                    throw customError(String.valueOf(c), startLine, startPos);

                case AFTER_POINT:
                    if(c == '.')
                    {
                        customConsumeChar();
                        this.customMode = CustomMode.AFTER_MS;
                        return new TPoint(startLine, startPos);
                    }
                    throw customError(String.valueOf(c), startLine, startPos);

                case AFTER_MS:
                    if(Character.isDigit(c))
                    {
                        int start = this.customIndex;
                        while(!customAtEnd() && Character.isDigit(customPeekChar()))
                        {
                            customConsumeChar();
                        }

                        this.customMode = CustomMode.AFTER_TIME_RBRACK;
                        return new TMs(this.customSource.substring(start, this.customIndex), startLine, startPos);
                    }
                    throw customError(String.valueOf(c), startLine, startPos);

                case AFTER_CATG:
                    if(c == ':')
                    {
                        customConsumeChar();
                        this.customMode = CustomMode.AFTER_META_TEXT;
                        return new TPoints(startLine, startPos);
                    }
                    throw customError(String.valueOf(c), startLine, startPos);

                default:
                    throw customError(String.valueOf(c), startLine, startPos);
            }
        }
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        Token customToken = nextCustomToken();
        if(customToken != null)
        {
            return customToken;
        }

        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBrack(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBrack(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPoints(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPoint(line, pos); }
    Token new4(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCatg(text, line, pos); }
    Token new5(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTitulo(text, line, pos); }
    Token new6(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new7(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMin(text, line, pos); }
    Token new8(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSeg(text, line, pos); }
    Token new9(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMs(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{0, 9, 1}, {10, 10, 2}, {11, 12, 1}, {13, 13, 3}, {14, 31, 1}, {32, 32, 4}, {33, 45, 1}, {46, 46, 5}, {47, 47, 1}, {48, 57, 6}, {58, 58, 7}, {59, 64, 1}, {65, 90, 8}, {91, 91, 9}, {92, 92, 1}, {93, 93, 10}, {94, 96, 1}, {97, 97, 11}, {98, 98, 12}, {99, 104, 13}, {105, 105, 14}, {106, 113, 13}, {114, 114, 15}, {115, 115, 13}, {116, 116, 16}, {117, 117, 13}, {118, 118, 17}, {119, 122, 13}, {123, 224, 1}, {225, 225, 18}, {226, 227, 1}, {228, 228, 19}, {229, 232, 1}, {233, 233, 20}, {234, 234, 1}, {235, 235, 21}, {236, 236, 1}, {237, 237, 22}, {238, 238, 1}, {239, 239, 23}, {240, 242, 1}, {243, 243, 24}, {244, 245, 1}, {246, 246, 25}, {247, 249, 1}, {250, 250, 26}, {251, 251, 1}, {252, 252, 27}, {253, 65535, 1}, },
            {{0, 47, 1}, {48, 57, 28}, {58, 64, 1}, {65, 90, 8}, {91, 96, 1}, {97, 122, 13}, {123, 65535, -2}, },
            {{0, 32, -2}, {33, 47, 1}, {48, 65535, -3}, },
            {{0, 65535, -4}, },
            {{0, 65535, -4}, },
            {{0, 65535, -3}, },
            {{0, 47, 1}, {48, 57, 6}, {58, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 96, -3}, {97, 113, 13}, {114, 114, 29}, {115, 122, 13}, {123, 65535, -2}, },
            {{0, 96, -3}, {97, 120, 13}, {121, 121, 30}, {122, 122, 13}, {123, 65535, -2}, },
            {{0, 65535, -3}, },
            {{0, 96, -3}, {97, 99, 13}, {100, 100, 31}, {101, 122, 13}, {123, 65535, -2}, },
            {{0, 96, -3}, {97, 100, 13}, {101, 101, 32}, {102, 122, 13}, {123, 65535, -2}, },
            {{0, 96, -3}, {97, 104, 13}, {105, 105, 33}, {106, 122, 13}, {123, 65535, -2}, },
            {{0, 100, -17}, {101, 101, 34}, {102, 65535, -17}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 5, 5, 5, 5, 3, 5, 2, 5, 0, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
