/* This file was generated by SableCC (http://www.sablecc.org/). */

package parser;

import node.*;
import analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTLBrack(@SuppressWarnings("unused") TLBrack node)
    {
        this.index = 0;
    }

    @Override
    public void caseTRBrack(@SuppressWarnings("unused") TRBrack node)
    {
        this.index = 1;
    }

    @Override
    public void caseTPoints(@SuppressWarnings("unused") TPoints node)
    {
        this.index = 2;
    }

    @Override
    public void caseTPoint(@SuppressWarnings("unused") TPoint node)
    {
        this.index = 3;
    }

    @Override
    public void caseTCatg(@SuppressWarnings("unused") TCatg node)
    {
        this.index = 4;
    }

    @Override
    public void caseTTitulo(@SuppressWarnings("unused") TTitulo node)
    {
        this.index = 5;
    }

    @Override
    public void caseTMin(@SuppressWarnings("unused") TMin node)
    {
        this.index = 6;
    }

    @Override
    public void caseTSeg(@SuppressWarnings("unused") TSeg node)
    {
        this.index = 7;
    }

    @Override
    public void caseTMs(@SuppressWarnings("unused") TMs node)
    {
        this.index = 8;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 9;
    }
}
