/* This file was generated by SableCC (http://www.sablecc.org/). */

package cc.node;

import cc.analysis.*;

@SuppressWarnings("nls")
public final class AColFragmento extends PFragmento
{
    private TDPuntos _dPuntos_;

    public AColFragmento()
    {
        // Constructor
    }

    public AColFragmento(
        @SuppressWarnings("hiding") TDPuntos _dPuntos_)
    {
        // Constructor
        setDPuntos(_dPuntos_);

    }

    @Override
    public Object clone()
    {
        return new AColFragmento(
            cloneNode(this._dPuntos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAColFragmento(this);
    }

    public TDPuntos getDPuntos()
    {
        return this._dPuntos_;
    }

    public void setDPuntos(TDPuntos node)
    {
        if(this._dPuntos_ != null)
        {
            this._dPuntos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dPuntos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dPuntos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dPuntos_ == child)
        {
            this._dPuntos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dPuntos_ == oldChild)
        {
            setDPuntos((TDPuntos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
