/* This file was generated by SableCC (http://www.sablecc.org/). */

package cc.node;

import cc.analysis.*;

@SuppressWarnings("nls")
public final class Start extends Node
{
    private PLinea _pLinea_;
    private EOF _eof_;

    public Start()
    {
        // Empty body
    }

    public Start(
        @SuppressWarnings("hiding") PLinea _pLinea_,
        @SuppressWarnings("hiding") EOF _eof_)
    {
        setPLinea(_pLinea_);
        setEOF(_eof_);
    }

    @Override
    public Object clone()
    {
        return new Start(
            cloneNode(this._pLinea_),
            cloneNode(this._eof_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseStart(this);
    }

    public PLinea getPLinea()
    {
        return this._pLinea_;
    }

    public void setPLinea(PLinea node)
    {
        if(this._pLinea_ != null)
        {
            this._pLinea_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pLinea_ = node;
    }

    public EOF getEOF()
    {
        return this._eof_;
    }

    public void setEOF(EOF node)
    {
        if(this._eof_ != null)
        {
            this._eof_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eof_ = node;
    }

    @Override
    void removeChild(Node child)
    {
        if(this._pLinea_ == child)
        {
            this._pLinea_ = null;
            return;
        }

        if(this._eof_ == child)
        {
            this._eof_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(Node oldChild, Node newChild)
    {
        if(this._pLinea_ == oldChild)
        {
            setPLinea((PLinea) newChild);
            return;
        }

        if(this._eof_ == oldChild)
        {
            setEOF((EOF) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    public String toString()
    {
        return "" +
            toString(this._pLinea_) +
            toString(this._eof_);
    }
}
