/* This file was generated by SableCC (http://www.sablecc.org/). */

package cc.node;

import cc.analysis.*;

@SuppressWarnings("nls")
public final class TDPuntos extends Token
{
    public TDPuntos()
    {
        super.setText(":");
    }

    public TDPuntos(int line, int pos)
    {
        super.setText(":");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDPuntos(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDPuntos(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDPuntos text.");
    }
}
