/* This file was generated by SableCC (http://www.sablecc.org/). */

package cc.analysis;

import cc.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseALinea(ALinea node);
    void caseATxtFragmento(ATxtFragmento node);
    void caseAColFragmento(AColFragmento node);

    void caseTCIzq(TCIzq node);
    void caseTCDer(TCDer node);
    void caseTDPuntos(TDPuntos node);
    void caseTTexto(TTexto node);
    void caseTSaltos(TSaltos node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
