/* This file was generated by SableCC (http://www.sablecc.org/). */

package cc.analysis;

import java.util.*;
import cc.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPLinea().apply(this);
        outStart(node);
    }

    public void inALinea(ALinea node)
    {
        defaultIn(node);
    }

    public void outALinea(ALinea node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALinea(ALinea node)
    {
        inALinea(node);
        {
            List<PFragmento> copy = new ArrayList<PFragmento>(node.getAfuera());
            Collections.reverse(copy);
            for(PFragmento e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getCDer() != null)
        {
            node.getCDer().apply(this);
        }
        {
            List<PFragmento> copy = new ArrayList<PFragmento>(node.getAdentro());
            Collections.reverse(copy);
            for(PFragmento e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getDPuntos() != null)
        {
            node.getDPuntos().apply(this);
        }
        if(node.getIzq() != null)
        {
            node.getIzq().apply(this);
        }
        if(node.getCIzq() != null)
        {
            node.getCIzq().apply(this);
        }
        outALinea(node);
    }

    public void inATxtFragmento(ATxtFragmento node)
    {
        defaultIn(node);
    }

    public void outATxtFragmento(ATxtFragmento node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATxtFragmento(ATxtFragmento node)
    {
        inATxtFragmento(node);
        if(node.getTexto() != null)
        {
            node.getTexto().apply(this);
        }
        outATxtFragmento(node);
    }

    public void inAColFragmento(AColFragmento node)
    {
        defaultIn(node);
    }

    public void outAColFragmento(AColFragmento node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAColFragmento(AColFragmento node)
    {
        inAColFragmento(node);
        if(node.getDPuntos() != null)
        {
            node.getDPuntos().apply(this);
        }
        outAColFragmento(node);
    }
}
