/* This file was generated by SableCC (http://www.sablecc.org/). */

package cc.node;

import cc.analysis.*;

@SuppressWarnings("nls")
public final class ATiempo extends PTiempo
{
    private TMin _min_;
    private TPoints _points_;
    private TSeg _seg_;
    private TPoint _point_;
    private TMs _ms_;

    public ATiempo()
    {
        // Constructor
    }

    public ATiempo(
        @SuppressWarnings("hiding") TMin _min_,
        @SuppressWarnings("hiding") TPoints _points_,
        @SuppressWarnings("hiding") TSeg _seg_,
        @SuppressWarnings("hiding") TPoint _point_,
        @SuppressWarnings("hiding") TMs _ms_)
    {
        // Constructor
        setMin(_min_);

        setPoints(_points_);

        setSeg(_seg_);

        setPoint(_point_);

        setMs(_ms_);

    }

    @Override
    public Object clone()
    {
        return new ATiempo(
            cloneNode(this._min_),
            cloneNode(this._points_),
            cloneNode(this._seg_),
            cloneNode(this._point_),
            cloneNode(this._ms_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATiempo(this);
    }

    public TMin getMin()
    {
        return this._min_;
    }

    public void setMin(TMin node)
    {
        if(this._min_ != null)
        {
            this._min_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._min_ = node;
    }

    public TPoints getPoints()
    {
        return this._points_;
    }

    public void setPoints(TPoints node)
    {
        if(this._points_ != null)
        {
            this._points_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._points_ = node;
    }

    public TSeg getSeg()
    {
        return this._seg_;
    }

    public void setSeg(TSeg node)
    {
        if(this._seg_ != null)
        {
            this._seg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._seg_ = node;
    }

    public TPoint getPoint()
    {
        return this._point_;
    }

    public void setPoint(TPoint node)
    {
        if(this._point_ != null)
        {
            this._point_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._point_ = node;
    }

    public TMs getMs()
    {
        return this._ms_;
    }

    public void setMs(TMs node)
    {
        if(this._ms_ != null)
        {
            this._ms_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ms_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._min_)
            + toString(this._points_)
            + toString(this._seg_)
            + toString(this._point_)
            + toString(this._ms_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._min_ == child)
        {
            this._min_ = null;
            return;
        }

        if(this._points_ == child)
        {
            this._points_ = null;
            return;
        }

        if(this._seg_ == child)
        {
            this._seg_ = null;
            return;
        }

        if(this._point_ == child)
        {
            this._point_ = null;
            return;
        }

        if(this._ms_ == child)
        {
            this._ms_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._min_ == oldChild)
        {
            setMin((TMin) newChild);
            return;
        }

        if(this._points_ == oldChild)
        {
            setPoints((TPoints) newChild);
            return;
        }

        if(this._seg_ == oldChild)
        {
            setSeg((TSeg) newChild);
            return;
        }

        if(this._point_ == oldChild)
        {
            setPoint((TPoint) newChild);
            return;
        }

        if(this._ms_ == oldChild)
        {
            setMs((TMs) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
