/* This file was generated by SableCC (http://www.sablecc.org/). */

package cc.node;

import cc.analysis.*;

@SuppressWarnings("nls")
public final class TSeg extends Token
{
    public TSeg(String text)
    {
        setText(text);
    }

    public TSeg(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSeg(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSeg(this);
    }
}
