/* This file was generated by SableCC (http://www.sablecc.org/). */

package cc.parser;

import cc.node.*;
import cc.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTCIzq(@SuppressWarnings("unused") TCIzq node)
    {
        this.index = 0;
    }

    @Override
    public void caseTCDer(@SuppressWarnings("unused") TCDer node)
    {
        this.index = 1;
    }

    @Override
    public void caseTDPuntos(@SuppressWarnings("unused") TDPuntos node)
    {
        this.index = 2;
    }

    @Override
    public void caseTTexto(@SuppressWarnings("unused") TTexto node)
    {
        this.index = 3;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 4;
    }
}
