/* This file was generated by SableCC (http://www.sablecc.org/). */

package analysis;

import java.util.*;
import node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPLine().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inADataLine(ADataLine node)
    {
        defaultIn(node);
    }

    public void outADataLine(ADataLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADataLine(ADataLine node)
    {
        inADataLine(node);
        if(node.getLBrack() != null)
        {
            node.getLBrack().apply(this);
        }
        if(node.getCatg() != null)
        {
            node.getCatg().apply(this);
        }
        if(node.getPoints() != null)
        {
            node.getPoints().apply(this);
        }
        if(node.getCadena() != null)
        {
            node.getCadena().apply(this);
        }
        if(node.getRBrack() != null)
        {
            node.getRBrack().apply(this);
        }
        outADataLine(node);
    }

    public void inASongLine(ASongLine node)
    {
        defaultIn(node);
    }

    public void outASongLine(ASongLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASongLine(ASongLine node)
    {
        inASongLine(node);
        if(node.getLBrack() != null)
        {
            node.getLBrack().apply(this);
        }
        if(node.getTiempo() != null)
        {
            node.getTiempo().apply(this);
        }
        if(node.getRBrack() != null)
        {
            node.getRBrack().apply(this);
        }
        if(node.getCadena() != null)
        {
            node.getCadena().apply(this);
        }
        outASongLine(node);
    }

    public void inATiempo(ATiempo node)
    {
        defaultIn(node);
    }

    public void outATiempo(ATiempo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATiempo(ATiempo node)
    {
        inATiempo(node);
        if(node.getMin() != null)
        {
            node.getMin().apply(this);
        }
        if(node.getPoints() != null)
        {
            node.getPoints().apply(this);
        }
        if(node.getSeg() != null)
        {
            node.getSeg().apply(this);
        }
        if(node.getPoint() != null)
        {
            node.getPoint().apply(this);
        }
        if(node.getMs() != null)
        {
            node.getMs().apply(this);
        }
        outATiempo(node);
    }

    public void inASimpleCadena(ASimpleCadena node)
    {
        defaultIn(node);
    }

    public void outASimpleCadena(ASimpleCadena node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASimpleCadena(ASimpleCadena node)
    {
        inASimpleCadena(node);
        if(node.getTitulo() != null)
        {
            node.getTitulo().apply(this);
        }
        outASimpleCadena(node);
    }

    public void inACompuestaCadena(ACompuestaCadena node)
    {
        defaultIn(node);
    }

    public void outACompuestaCadena(ACompuestaCadena node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACompuestaCadena(ACompuestaCadena node)
    {
        inACompuestaCadena(node);
        if(node.getTitulo() != null)
        {
            node.getTitulo().apply(this);
        }
        if(node.getCadena() != null)
        {
            node.getCadena().apply(this);
        }
        outACompuestaCadena(node);
    }
}
