/* This file was generated by SableCC (http://www.sablecc.org/). */

package cc.node;

import cc.analysis.*;

@SuppressWarnings("nls")
public final class ACompuestaCadena extends PCadena
{
    private TTitulo _titulo_;
    private PCadena _cadena_;

    public ACompuestaCadena()
    {
        // Constructor
    }

    public ACompuestaCadena(
        @SuppressWarnings("hiding") TTitulo _titulo_,
        @SuppressWarnings("hiding") PCadena _cadena_)
    {
        // Constructor
        setTitulo(_titulo_);

        setCadena(_cadena_);

    }

    @Override
    public Object clone()
    {
        return new ACompuestaCadena(
            cloneNode(this._titulo_),
            cloneNode(this._cadena_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACompuestaCadena(this);
    }

    public TTitulo getTitulo()
    {
        return this._titulo_;
    }

    public void setTitulo(TTitulo node)
    {
        if(this._titulo_ != null)
        {
            this._titulo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._titulo_ = node;
    }

    public PCadena getCadena()
    {
        return this._cadena_;
    }

    public void setCadena(PCadena node)
    {
        if(this._cadena_ != null)
        {
            this._cadena_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cadena_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._titulo_)
            + toString(this._cadena_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._titulo_ == child)
        {
            this._titulo_ = null;
            return;
        }

        if(this._cadena_ == child)
        {
            this._cadena_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._titulo_ == oldChild)
        {
            setTitulo((TTitulo) newChild);
            return;
        }

        if(this._cadena_ == oldChild)
        {
            setCadena((PCadena) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
