/* This file was generated by SableCC (http://www.sablecc.org/). */

package cc.node;

import java.util.*;
import cc.analysis.*;

@SuppressWarnings("nls")
public final class ALinea extends PLinea
{
    private TCIzq _cIzq_;
    private TTexto _izq_;
    private TDPuntos _dPuntos_;
    private final LinkedList<PFragmento> _adentro_ = new LinkedList<PFragmento>();
    private TCDer _cDer_;
    private final LinkedList<PFragmento> _afuera_ = new LinkedList<PFragmento>();

    public ALinea()
    {
        // Constructor
    }

    public ALinea(
        @SuppressWarnings("hiding") TCIzq _cIzq_,
        @SuppressWarnings("hiding") TTexto _izq_,
        @SuppressWarnings("hiding") TDPuntos _dPuntos_,
        @SuppressWarnings("hiding") List<?> _adentro_,
        @SuppressWarnings("hiding") TCDer _cDer_,
        @SuppressWarnings("hiding") List<?> _afuera_)
    {
        // Constructor
        setCIzq(_cIzq_);

        setIzq(_izq_);

        setDPuntos(_dPuntos_);

        setAdentro(_adentro_);

        setCDer(_cDer_);

        setAfuera(_afuera_);

    }

    @Override
    public Object clone()
    {
        return new ALinea(
            cloneNode(this._cIzq_),
            cloneNode(this._izq_),
            cloneNode(this._dPuntos_),
            cloneList(this._adentro_),
            cloneNode(this._cDer_),
            cloneList(this._afuera_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALinea(this);
    }

    public TCIzq getCIzq()
    {
        return this._cIzq_;
    }

    public void setCIzq(TCIzq node)
    {
        if(this._cIzq_ != null)
        {
            this._cIzq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cIzq_ = node;
    }

    public TTexto getIzq()
    {
        return this._izq_;
    }

    public void setIzq(TTexto node)
    {
        if(this._izq_ != null)
        {
            this._izq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._izq_ = node;
    }

    public TDPuntos getDPuntos()
    {
        return this._dPuntos_;
    }

    public void setDPuntos(TDPuntos node)
    {
        if(this._dPuntos_ != null)
        {
            this._dPuntos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dPuntos_ = node;
    }

    public LinkedList<PFragmento> getAdentro()
    {
        return this._adentro_;
    }

    public void setAdentro(List<?> list)
    {
        for(PFragmento e : this._adentro_)
        {
            e.parent(null);
        }
        this._adentro_.clear();

        for(Object obj_e : list)
        {
            PFragmento e = (PFragmento) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._adentro_.add(e);
        }
    }

    public TCDer getCDer()
    {
        return this._cDer_;
    }

    public void setCDer(TCDer node)
    {
        if(this._cDer_ != null)
        {
            this._cDer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cDer_ = node;
    }

    public LinkedList<PFragmento> getAfuera()
    {
        return this._afuera_;
    }

    public void setAfuera(List<?> list)
    {
        for(PFragmento e : this._afuera_)
        {
            e.parent(null);
        }
        this._afuera_.clear();

        for(Object obj_e : list)
        {
            PFragmento e = (PFragmento) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._afuera_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cIzq_)
            + toString(this._izq_)
            + toString(this._dPuntos_)
            + toString(this._adentro_)
            + toString(this._cDer_)
            + toString(this._afuera_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cIzq_ == child)
        {
            this._cIzq_ = null;
            return;
        }

        if(this._izq_ == child)
        {
            this._izq_ = null;
            return;
        }

        if(this._dPuntos_ == child)
        {
            this._dPuntos_ = null;
            return;
        }

        if(this._adentro_.remove(child))
        {
            return;
        }

        if(this._cDer_ == child)
        {
            this._cDer_ = null;
            return;
        }

        if(this._afuera_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cIzq_ == oldChild)
        {
            setCIzq((TCIzq) newChild);
            return;
        }

        if(this._izq_ == oldChild)
        {
            setIzq((TTexto) newChild);
            return;
        }

        if(this._dPuntos_ == oldChild)
        {
            setDPuntos((TDPuntos) newChild);
            return;
        }

        for(ListIterator<PFragmento> i = this._adentro_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PFragmento) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._cDer_ == oldChild)
        {
            setCDer((TCDer) newChild);
            return;
        }

        for(ListIterator<PFragmento> i = this._afuera_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PFragmento) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
