/* This file was generated by SableCC (http://www.sablecc.org/). */

package cc.node;

import cc.analysis.*;

@SuppressWarnings("nls")
public final class TCIzq extends Token
{
    public TCIzq()
    {
        super.setText("[");
    }

    public TCIzq(int line, int pos)
    {
        super.setText("[");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCIzq(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCIzq(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCIzq text.");
    }
}
