/* This file was generated by SableCC (http://www.sablecc.org/). */

package cc.analysis;

import cc.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseADataLine(ADataLine node);
    void caseASongLine(ASongLine node);
    void caseATiempo(ATiempo node);
    void caseASimpleCadena(ASimpleCadena node);
    void caseACompuestaCadena(ACompuestaCadena node);

    void caseTLBrack(TLBrack node);
    void caseTRBrack(TRBrack node);
    void caseTPoints(TPoints node);
    void caseTPoint(TPoint node);
    void caseTCatg(TCatg node);
    void caseTTitulo(TTitulo node);
    void caseTBlank(TBlank node);
    void caseTMin(TMin node);
    void caseTSeg(TSeg node);
    void caseTMs(TMs node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
