/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ADataLine extends PLine
{
    private TLBrack _lBrack_;
    private TCatg _catg_;
    private TPoints _points_;
    private PCadena _cadena_;
    private TRBrack _rBrack_;

    public ADataLine()
    {
        // Constructor
    }

    public ADataLine(
        @SuppressWarnings("hiding") TLBrack _lBrack_,
        @SuppressWarnings("hiding") TCatg _catg_,
        @SuppressWarnings("hiding") TPoints _points_,
        @SuppressWarnings("hiding") PCadena _cadena_,
        @SuppressWarnings("hiding") TRBrack _rBrack_)
    {
        // Constructor
        setLBrack(_lBrack_);

        setCatg(_catg_);

        setPoints(_points_);

        setCadena(_cadena_);

        setRBrack(_rBrack_);

    }

    @Override
    public Object clone()
    {
        return new ADataLine(
            cloneNode(this._lBrack_),
            cloneNode(this._catg_),
            cloneNode(this._points_),
            cloneNode(this._cadena_),
            cloneNode(this._rBrack_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADataLine(this);
    }

    public TLBrack getLBrack()
    {
        return this._lBrack_;
    }

    public void setLBrack(TLBrack node)
    {
        if(this._lBrack_ != null)
        {
            this._lBrack_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lBrack_ = node;
    }

    public TCatg getCatg()
    {
        return this._catg_;
    }

    public void setCatg(TCatg node)
    {
        if(this._catg_ != null)
        {
            this._catg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._catg_ = node;
    }

    public TPoints getPoints()
    {
        return this._points_;
    }

    public void setPoints(TPoints node)
    {
        if(this._points_ != null)
        {
            this._points_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._points_ = node;
    }

    public PCadena getCadena()
    {
        return this._cadena_;
    }

    public void setCadena(PCadena node)
    {
        if(this._cadena_ != null)
        {
            this._cadena_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cadena_ = node;
    }

    public TRBrack getRBrack()
    {
        return this._rBrack_;
    }

    public void setRBrack(TRBrack node)
    {
        if(this._rBrack_ != null)
        {
            this._rBrack_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rBrack_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lBrack_)
            + toString(this._catg_)
            + toString(this._points_)
            + toString(this._cadena_)
            + toString(this._rBrack_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lBrack_ == child)
        {
            this._lBrack_ = null;
            return;
        }

        if(this._catg_ == child)
        {
            this._catg_ = null;
            return;
        }

        if(this._points_ == child)
        {
            this._points_ = null;
            return;
        }

        if(this._cadena_ == child)
        {
            this._cadena_ = null;
            return;
        }

        if(this._rBrack_ == child)
        {
            this._rBrack_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lBrack_ == oldChild)
        {
            setLBrack((TLBrack) newChild);
            return;
        }

        if(this._catg_ == oldChild)
        {
            setCatg((TCatg) newChild);
            return;
        }

        if(this._points_ == oldChild)
        {
            setPoints((TPoints) newChild);
            return;
        }

        if(this._cadena_ == oldChild)
        {
            setCadena((PCadena) newChild);
            return;
        }

        if(this._rBrack_ == oldChild)
        {
            setRBrack((TRBrack) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
