/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ASimpleCadena extends PCadena
{
    private TTitulo _titulo_;

    public ASimpleCadena()
    {
        // Constructor
    }

    public ASimpleCadena(
        @SuppressWarnings("hiding") TTitulo _titulo_)
    {
        // Constructor
        setTitulo(_titulo_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleCadena(
            cloneNode(this._titulo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleCadena(this);
    }

    public TTitulo getTitulo()
    {
        return this._titulo_;
    }

    public void setTitulo(TTitulo node)
    {
        if(this._titulo_ != null)
        {
            this._titulo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._titulo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._titulo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._titulo_ == child)
        {
            this._titulo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._titulo_ == oldChild)
        {
            setTitulo((TTitulo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
