/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ASongLine extends PLine
{
    private TLBrack _lBrack_;
    private PTiempo _tiempo_;
    private TRBrack _rBrack_;
    private PCadena _cadena_;

    public ASongLine()
    {
        // Constructor
    }

    public ASongLine(
        @SuppressWarnings("hiding") TLBrack _lBrack_,
        @SuppressWarnings("hiding") PTiempo _tiempo_,
        @SuppressWarnings("hiding") TRBrack _rBrack_,
        @SuppressWarnings("hiding") PCadena _cadena_)
    {
        // Constructor
        setLBrack(_lBrack_);

        setTiempo(_tiempo_);

        setRBrack(_rBrack_);

        setCadena(_cadena_);

    }

    @Override
    public Object clone()
    {
        return new ASongLine(
            cloneNode(this._lBrack_),
            cloneNode(this._tiempo_),
            cloneNode(this._rBrack_),
            cloneNode(this._cadena_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASongLine(this);
    }

    public TLBrack getLBrack()
    {
        return this._lBrack_;
    }

    public void setLBrack(TLBrack node)
    {
        if(this._lBrack_ != null)
        {
            this._lBrack_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lBrack_ = node;
    }

    public PTiempo getTiempo()
    {
        return this._tiempo_;
    }

    public void setTiempo(PTiempo node)
    {
        if(this._tiempo_ != null)
        {
            this._tiempo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tiempo_ = node;
    }

    public TRBrack getRBrack()
    {
        return this._rBrack_;
    }

    public void setRBrack(TRBrack node)
    {
        if(this._rBrack_ != null)
        {
            this._rBrack_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rBrack_ = node;
    }

    public PCadena getCadena()
    {
        return this._cadena_;
    }

    public void setCadena(PCadena node)
    {
        if(this._cadena_ != null)
        {
            this._cadena_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cadena_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lBrack_)
            + toString(this._tiempo_)
            + toString(this._rBrack_)
            + toString(this._cadena_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lBrack_ == child)
        {
            this._lBrack_ = null;
            return;
        }

        if(this._tiempo_ == child)
        {
            this._tiempo_ = null;
            return;
        }

        if(this._rBrack_ == child)
        {
            this._rBrack_ = null;
            return;
        }

        if(this._cadena_ == child)
        {
            this._cadena_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lBrack_ == oldChild)
        {
            setLBrack((TLBrack) newChild);
            return;
        }

        if(this._tiempo_ == oldChild)
        {
            setTiempo((PTiempo) newChild);
            return;
        }

        if(this._rBrack_ == oldChild)
        {
            setRBrack((TRBrack) newChild);
            return;
        }

        if(this._cadena_ == oldChild)
        {
            setCadena((PCadena) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
